CREATE TABLE IF NOT EXISTS clients (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  cpf VARCHAR (11) NOT NULL,
  birthday DATE NOT NULL,
  phone VARCHAR (11) NOT NULL,
  email VARCHAR (100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS accounts (
  id INTEGER PRIMARY KEY,
  owner INTEGER NOT NULL REFERENCES clients (id) ON DELETE CASCADE,
  balance DECIMAL (10, 2) NOT NULL DEFAULT 0.0
);

CREATE TYPE transfer_type AS ENUM ('DOC', 'TED', 'PIX');

CREATE TABLE IF NOT EXISTS transfers (
  id SERIAL PRIMARY KEY,
  source INTEGER NOT NULL REFERENCES accounts (id) ON DELETE NO ACTION,
  target INTEGER NOT NULL REFERENCES accounts (id) ON DELETE NO ACTION,
  type transfer_type NOT NULL,
  value DECIMAL(9, 2) NOT NULL CHECK (value > 0.0),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
